Iter9
sebasttiano/Blackbird pull request #11
Opened 2024-01-15 11:04 UTC by sebasttiano

2024-01-19 21:05 UTC, bambruysk requested changes
Чуть доработать надо

2024-01-19 21:05 UTC, bambruysk commented on internal/common/clients.go
> +	client := &http.Client{}
чтобы не создавать клиент каждый раз его можно было сделать полем клиента

2024-01-19 21:05 UTC, bambruysk commented on internal/common/clients.go
> +func (c HTTPClient) Post(urlSuffix string, body io.Reader, headers []string) (*http.Response, error) {
обычно чттобы не возиться с рзбиеням по строкам хидеры храним как мапу, так как по сути оно и есть

2024-01-19 21:05 UTC, bambruysk commented on internal/common/clients.go
> +			splitHeader := strings.Split(header, ":")
здесь надо бы использовать SplitN -  значение хидера может содержать любые символы

2024-01-19 21:05 UTC, bambruysk commented on internal/common/clients.go
> +	var retries = 3
эти значения лучше вынести в конфигурацию

2024-01-19 21:05 UTC, bambruysk commented on cmd/agent/main.go
> +			if strings.Contains(err.Error(), "connect: connection refused") {
лучше пусть клиент возвращает ошибку типа ErrConnect, а здесь проверять через errors.Is

2024-01-19 21:05 UTC, bambruysk commented on internal/common/scheduler.go
> +}
эту рутинку лучше засунуть в файловое хранилище

2024-01-19 21:05 UTC, bambruysk commented on internal/handlers/handler.go
> +	if err := storage.SrvFacility.LocalStorage.GetModelValue(&metrics); err != nil {
это паровозик явно требует рефакторинга - зачем такая длинная цепочка?

2024-01-19 21:05 UTC, bambruysk commented on internal/handlers/handler.go
> +func GetMetricJSON(res http.ResponseWriter, req *http.Request) {
сделай эти функции методами структуры в которй можно хранить ссылку на хранилище в виде интерфейсной переменной - это избавит от необходимости делать эти цепочки

2024-01-19 21:05 UTC, bambruysk commented on internal/handlers/handler.go
> +		io.WriteString(res, err.Error()+"\n")
можно было бы использовать http.Error?

2024-01-19 21:05 UTC, bambruysk commented on internal/handlers/middleware.go
> +			"size", responseData.size,
здесть лучше использовать zap.Field

2024-01-19 21:05 UTC, bambruysk commented on internal/storage/storage.go
> +func GetCurrentStorage() *HandleMemStorage {
зачем нам это если SrvFacility - экспортируемое?

2024-01-24 20:27 UTC, sebasttiano commented on internal/handlers/handler.go
> +		io.WriteString(res, err.Error()+"\n")
Я это использовал ранее, потом меня достали логи "http: superfluous response.WriteHeader" и кажется я таким образом боролся с ними...
Вернул.

2024-01-24 20:30 UTC, sebasttiano commented on internal/handlers/handler.go
> +func GetMetricJSON(res http.ResponseWriter, req *http.Request) {
Добавид структуру
```
type ServerViews struct {
	store     storage.HandleMemStorage
	templates templates.HTMLTemplates
}
```

2024-01-24 21:11 UTC, sebasttiano commented on internal/common/clients.go
> +	client := &http.Client{}
Переделал клиента
```
// HTTPClient simple client
type HTTPClient struct {
	url          string
	client       *http.Client
	retryIn      int
	retries      int
	ClientErrors HTTPClientErrors
}
```

2024-01-24 21:12 UTC, sebasttiano commented on internal/common/clients.go
> +func (c HTTPClient) Post(urlSuffix string, body io.Reader, headers []string) (*http.Response, error) {
Сделала через мапу

2024-01-24 21:12 UTC, sebasttiano commented on internal/common/clients.go
> +			splitHeader := strings.Split(header, ":")
Неактуально после перехода на мапу выше

2024-01-24 21:14 UTC, sebasttiano commented on internal/common/clients.go
> +	var retries = 3
Вынес в agent/flags.go
```
var (
	serverIPAddr           string
	flagLogLevel           string
	pollInterval           int64
	reportInterval         int64
	httpClientRetry        = 3
	httpClientRetryTimeout = 3
)
```

2024-01-24 21:16 UTC, sebasttiano commented on cmd/agent/main.go
> +			if strings.Contains(err.Error(), "connect: connection refused") {
internal/common/clients
```
func NewHTTPClientErrors() HTTPClientErrors {
	return HTTPClientErrors{
		ErrConnect: errors.New("client couldn`t connect to server"),
	}
}
```
cmd/agent/main.go
```
			if errors.Is(err, client.ClientErrors.ErrConnect)
```

2024-01-24 21:17 UTC, sebasttiano commented on internal/common/scheduler.go
> +}
Перенес в пакет storage

2024-01-24 21:18 UTC, sebasttiano commented on internal/handlers/handler.go
> +	if err := storage.SrvFacility.LocalStorage.GetModelValue(&metrics); err != nil {
```
type ServerViews struct {
	store     storage.HandleMemStorage
	templates templates.HTMLTemplates
}
```

2024-01-24 21:18 UTC, sebasttiano commented on internal/handlers/middleware.go
> +			"size", responseData.size,
Сделал

2024-01-24 21:18 UTC, sebasttiano commented on internal/storage/storage.go
> +func GetCurrentStorage() *HandleMemStorage {
Убрал

2024-01-29 18:05 UTC, bambruysk approved these changes
принято

2024-01-30 12:48 UTC, merged