Iter13
sebasttiano/Blackbird pull request #15
Opened 2024-02-04 19:06 UTC by sebasttiano

2024-02-05 11:28 UTC, bambruysk requested changes
Нужно немного доработать по замечаниям

2024-02-05 11:28 UTC, bambruysk commented on cmd/server/app.go
> +	conn  *sqlx.DB
а зачем app хранит соединение с БД? лучше пусть это внутри store где-то происходит

2024-02-05 11:28 UTC, bambruysk commented on internal/handlers/handler.go
> +
Контекст должно прихожить из запроса r.Context()

2024-02-05 11:28 UTC, bambruysk commented on internal/handlers/handler.go
> +		logger.Log.Debug("error encoding response", zap.Error(err))
это вот явно какая-то ошибка, так что лучше писать как log.Error

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/client.go
> +}
а разве эти два типа ошибок могут возникнуть одновременно?

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/client.go
> +		tx.MustExecContext(ctx, sqlInsert, metric.Name, newValue)
функции типа MustXXX - бросают панику если что не так, их применение должно быть ограничено теми ситуациями, когда мы можем себе позволить паниковвать ( например,тесты) либо когда невозможно вернуть ошибку. В общем в этом случае лучше ее не использовать

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/client.go
> +	}
если не нашли метрику с таким именем, то как она будет вставлена ниже? Непонятно.
Второе, лучше всегда стараться уложиться в один запрос, так как несколько запросов в одну базу в рамках одного запроса со стороны клиента без использования транзакций могут вызвать проблемы при параллельном выполнении запросов. То есть если приходят нескольоко параллельных запросов в одну и ту же метрику, легко может случится такая последовательность событий ( 1 и 2 номер горутины) 

- 1. запросили метрику
- 1. метрики нет
- 1. решили вставить новую
- (runtime) переключились на другую горутину 2
- 2. запросили метрику
- 2. метрики нет
- 2. вставили новую
-  (runtime) переключились на другую горутину 1
- 1. вставляем новую метрику
- 1. конфликт ошибка ой ой!!!

Чтобы избежать этого можно использовать транзакцию, или запрос  INSERT .... ON CONFLICT

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/client.go
> +}
а чем она отличается от обычной ошибки?

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/db.go
> +var PGError *pgconn.PgError
не надо делать этот указатель глобальным - можно поймать ошибку из соседней горутины

2024-02-05 11:28 UTC, bambruysk commented on internal/storage/db.go
> +			}
здесь наверное rerurn нужен?

2024-02-06 20:35 UTC, sebasttiano commented on cmd/server/app.go
> +	conn  *sqlx.DB
Убрал из app

2024-02-06 20:55 UTC, sebasttiano commented on internal/handlers/handler.go
> +
Изменил везде

2024-02-06 20:59 UTC, sebasttiano commented on internal/handlers/handler.go
> +		logger.Log.Debug("error encoding response", zap.Error(err))
сменил на Error везде в таких  случаях

2024-02-06 21:10 UTC, sebasttiano commented on internal/storage/client.go
> +		tx.MustExecContext(ctx, sqlInsert, metric.Name, newValue)
Поменял на tx.ExecContext

2024-02-06 21:29 UTC, sebasttiano commented on internal/storage/client.go
> +}
Добавил в нее логирование количества неуспешных ретраев. + упаковку оригинальной ошибки

2024-02-06 21:41 UTC, sebasttiano commented on internal/storage/db.go
> +var PGError *pgconn.PgError
Сделал локальным

2024-02-06 21:54 UTC, sebasttiano commented on internal/storage/db.go
> +			}
Сделал возврат ошибки

2024-02-06 22:06 UTC, sebasttiano commented on internal/storage/client.go
> +}
Убрал  ErrDBConnect, т.к. он не использовался. Но, если честно не понял вопроса тут. Да не могут они произойти одновременно, но я в этой структуре просто собираю кастомные ошибки для клиента...

2024-02-06 23:02 UTC, sebasttiano commented on internal/storage/client.go
> +	}
1. Там по id = 0 условие, при котором выбирается либо инсерт, либо апдейт

Сделал поле name UNIQUE CONSTRAINT, переделал на один запрос (INSERT ... ON CONFLICT), вместо трех. Стало гораздо лаконичнее и безопаснее)

2024-02-10 08:31 UTC, bambruysk commented on internal/storage/client.go
> +}
Обычно просто ошибки выводят на уровень пакета в var или вообще в отдельный подход. Но имеет место быть)

2024-02-10 08:31 UTC, bambruysk commented on internal/storage/client.go
> +	}
👍

2024-02-10 08:33 UTC, bambruysk approved these changes
Принято

2024-02-15 19:37 UTC, merged