Iter15
sebasttiano/Blackbird pull request #17
Opened 2024-02-18 19:33 UTC by sebasttiano

2024-02-20 06:44 UTC, bambruysk requested changes
Надо доработать в части отправки, Процесс должен запускаться непрерывно и с заданным интервалом

2024-02-20 06:44 UTC, bambruysk commented on cmd/agent/main.go
> +	}
получается мы однократно исполняем это? За время работы агента? Здесь должен быть непрерывно запущенный процесс, до тех пор пока агент не остановят

2024-02-20 06:44 UTC, bambruysk commented on internal/handlers/middleware.go
> +		ow := res
а зачем, может просто переимновать аргумент если хочется?

2024-02-21 23:02 UTC, sebasttiano commented on cmd/agent/main.go
> +	}
Предполагается, что в самом методе IterateStructFieldsAndSend  имеется цикл с тикером интервальным и с остановкой по сигналу или критической ошибке. Сейчас сделал, чтобы только логировал ошибки при отправке и сделал в виде паттерна worker pool, добавил очередей. Остановка по SIGTERM и etc

2024-02-21 23:05 UTC, sebasttiano commented on internal/handlers/middleware.go
> +		ow := res
Не особо понял, что именно изменить. Переименовал аргумент на данный (res), чтобы было как везде. А саму миддлеварю взял из примера с Алисой:
```
		// по умолчанию устанавливаем оригинальный http.ResponseWriter как тот,
		// который будем передавать следующей функции
		ow := w
```

2024-02-22 17:29 UTC, bambruysk approved these changes
Принято

2024-03-01 09:32 UTC, merged