Iter18
sebasttiano/Blackbird pull request #19
Opened 2024-04-10 17:33 UTC by sebasttiano

2024-04-12 14:12 UTC, bambruysk requested changes
похоже профили снимались без нагрузки

Что было соптимизированно в результате бенчмарка?

2024-04-12 14:12 UTC, bambruysk commented on internal/agent/agent_test.go
> +			}
а зачем эта возня с каналами - если все равно линейно получается? 
может дать им большой канал и пуст они туда записывают - на запуская это в горутинах?

2024-04-12 14:12 UTC, bambruysk commented on internal/agent/agent_test.go
> +		b.ReportMetric(float64(jobsMetricCount)/float64(b.N), "metric_jobs/op")
есть ощущение что тут всегда 1?

Я запустил сейча сэтот бенчмарк - там всего одна операция - что-то не так

2024-04-12 14:12 UTC, bambruysk commented on internal/agent/agent_test.go
> +		b.ReportMetric(float64(jobsMetricCount)/float64(b.N), "metric_jobs/op")
for range ждет закрытия канала -  а его никто не закрывает

2024-04-15 23:18 UTC, sebasttiano commented on internal/agent/agent_test.go
> +		b.ReportMetric(float64(jobsMetricCount)/float64(b.N), "metric_jobs/op")
Переделал без горутин и побольше рандома.

2024-04-15 23:19 UTC, sebasttiano commented on internal/agent/agent_test.go
> +			}
Убрал горутины

2024-04-15 23:22 UTC, sebasttiano commented
> похоже профили снимались без нагрузки
> 
> Что было соптимизированно в результате бенчмарка?



> похоже профили снимались без нагрузки
> 
> Что было соптимизированно в результате бенчмарка?

Добавил встроенные http профилеры в сервер и агент.
Оптимизировал пакет compress с заменой на другой.

2024-04-18 20:36 UTC, bambruysk approved these changes
Принято

2024-04-18 20:36 UTC, bambruysk commented on internal/agent/agent_test.go
> +		b.ReportMetric(float64(jobsMetricCount)/float64(b.N), "metric_jobs/op")
хорошо

2024-04-20 14:26 UTC, merged