Iter25
sebasttiano/Blackbird pull request #27
Opened 2024-06-08 17:08 UTC by sebasttiano

2024-06-11 23:49 UTC, Bazys requested changes
покрытие тестами должно быть как минимум 55%, я наблюдаю  19.4%
Есть один вопрос. но самое главное, то не проверяешь на ошибки

2024-06-11 23:49 UTC, Bazys commented on internal/models/models.go
> +	var metrics []*Metrics
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
metrics := make([]*Metrics, 0, len(m.Set))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-06-13 14:15 UTC, sebasttiano commented on internal/models/models.go
> +	var metrics []*Metrics
Я это понимал, и пытался сделать, но ставил в длину слайса, а в не capacity

2024-06-14 18:59 UTC, sebasttiano commented on internal/models/models.go
> +	var metrics []*Metrics
Добавил коды и их обработку. Покрытие тестами поднял до 25%, на днях дойду до выше 55%

2024-06-16 17:58 UTC, Bazys requested changes
1. Prealloc еще прпопустил в нескольких местах
2. С неймингом не до конца всё корректно
3. Очень много неиспользуемых параметров
4. if else - тоже много раз встречается

2024-06-16 17:58 UTC, Bazys commented on internal/service/service.go
>  type ErrRetryDB struct {
Именование ошибок должно быть в виде `XxxError` (это про 26 стр)

https://go.dev/wiki/Errors#naming

2024-06-16 17:58 UTC, Bazys commented on internal/handlers/grpc.go
> +		} else {
Использование `else` после `return` в блоке `if` избыточно. Потому что если условие в `if` истинно, функция завершится и вернёт значение на этом этапе, и выполнение кода дальше не пойдет. Это значит, что все, что находится в `else`, будет выполнено только если условие `if` не истинно, и нет нужды явно оборачивать этот код в `else`. Таким образом, код становится проще и уменьшается его вложенность, что облегчает его чтение и понимание. Поэтому вместо твоего варианта типа:
```go
if условие {
    return что-то
} else {
    // другой код
}
```
Можно написать кратко:
```go
if условие {
    return что-то
}
// другой код
```
Доп. ссылки:
1. [Effective Go](https://go.dev/doc/effective_go#if)
2. [Uber Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting)
3. [Code Health: Reduce Nesting, Reduce Complexity ](https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html)

2024-06-16 17:58 UTC, Bazys commented on internal/handlers/interceptors.go
> +	return logging.LoggerFunc(func(ctx context.Context, lvl logging.Level, msg string, fields ...any) {
Параметр функции, названный `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-16 17:58 UTC, Bazys commented on cmd/server/main.go
>  	_ "embed"
импорты не отсортированы.
`goimports` наше все

2024-06-16 17:58 UTC, Bazys commented on internal/service/service.go
>  	SaveFilePath  string
замечание к имени структуры

снаружи выглядит как `service.ServiceSettings` - масло масляное

1. https://go.dev/blog/package-names
2. https://go.dev/doc/effective_go#names
3. https://google.github.io/styleguide/go/decisions.html

2024-06-24 08:43 UTC, sebasttiano commented on cmd/server/main.go
>  	_ "embed"
Прошелся goimports.

2024-06-24 17:08 UTC, sebasttiano commented on internal/service/service.go
>  	SaveFilePath  string
Поправил

2024-06-25 20:58 UTC, Bazys approved these changes
хорошая работа проделана. А насчет wg в структруе подумай, точно ей там место? может проще каждый раз новую использовать?

2024-06-25 20:58 UTC, Bazys commented on internal/config/config.go
> +	WG               sync.WaitGroup
не самая лучшая практика добавлять wg в структуру. Как знаешь там под капотом атомик и счетчик будет глобальным для всех кто пользуется конфигом. Не уверен что именно для этого и задумывалось. Может ты посмотришь в сторону других паттернов.

2024-06-25 20:58 UTC, Bazys commented on cmd/agent/main.go
> +	a, err := agent.NewAgent("http://"+cfg.ServerIPAddr, 3, 1, cfg.SecretKey, publicKey, cfg.GRPSServerIPAddr)
ты уверен что "http://" надо захардкодить? а завтра будет "https://"  
Там есть грязный хак с указанием просто // - но подумай как это сделать по другому.

2024-06-25 20:58 UTC, Bazys commented on cmd/agent/main.go
комментарий к строке ниже 
jobsMetrics := make(chan agent.MetricsSet, 10)

почему именно 10? а не 100 или 5000? 

в принципе считается использование буферизированных каналов > 1 плохой практикой.
https://github.com/uber-go/guide/blob/master/style.md#channel-size-is-one-or-none
но убер не последняя интсанция, это просто что с ходу вспомнил.

А если это делается для rate limit то цифру надо в настройку выносить.

2024-06-26 08:52 UTC, merged