Iter5
sebasttiano/Blackbird pull request #5
Opened 2023-12-20 16:30 UTC by sebasttiano

2023-12-21 17:10 UTC, bambruysk requested changes
Нужно доработать

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		if (startTime-time.Now().Unix())%reportInterval == 0 {
для вычислений с временем лучше использовать методы из пакета time - там есть и сложение и вычитание и сравнение

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		if (startTime-time.Now().Unix())%reportInterval == 0 {
А если у нас интервал отправки не кратен интервалу сбора?

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		if field.Name == "PollCount" {
если уж опираться на рефлексию то лучше ее и использовать https://pkg.go.dev/reflect#Value.CanInt например

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +			panic(err)
не надо паниковать - лучше вернуть ошибку и обработать

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		defer res.Body.Close()
ошибка -  defer вызывается в цикле из-за чего может утекать память и прочие неприятности. В этом случае лучше обойтись без него

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		panic(err)
не паникуем

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +		r.Header.Add(splitHeader[0], splitHeader[1])
мы разбили строку на две части - но не проверили что их действительно две в слайсе - это может привести к панике OutOfBounds

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main_test.go
> +			assert.Equal(t, tt.args.reportInterval, endTime-startTime)
Этот тест проверяет только время исполнения функции, а остальное?

2023-12-21 17:10 UTC, bambruysk commented on cmd/server/main.go
> +	return err
можно просто return http.ListenAndServe(flagRunAddr, handlers.InitRouter())

2023-12-21 17:10 UTC, bambruysk commented on internal/handlers/handler.go
> +	tmpl, err := template.ParseFiles(fp)
парсинг файлов тяжелая операция-  лучше проделать ее одинт раз на старте приложения чем при каждом запросе

2023-12-21 17:10 UTC, bambruysk commented on internal/handlers/handler.go
> +var localStorage = storage.NewMemStorage()
использовать глобальную переменную - даже потокбезопасную не очень хорошо
Лучше создать структуру и в ней это хранить

Ну и импортировать напрямую отсюда не стоит так как это лишние зависимости

2023-12-21 17:10 UTC, bambruysk commented on internal/handlers/handler.go
> +	}
А здесь лучше бы явно указать статус

2023-12-21 17:10 UTC, bambruysk commented on internal/handlers/handler.go
> +}
Чет не понял - тут мультиплексор создается - выше - chi роутер

2023-12-21 17:10 UTC, bambruysk commented on internal/storage/storage.go
> +		return nil, errors.New("error: UNKNOWN METRIC TYPE. Only gauge and counter are available")
текст ошибки по гошным стайлам пишется маленькими буквами

2023-12-21 17:10 UTC, bambruysk commented on cmd/agent/main.go
> +func GetMetrics(pollInterval int64, reportInterval int64, stopLimit int, client HTTPClient) {
лучше бы параметры этой фукнции собрать в структуру, а ее саму сделать методом этой структуры

2023-12-21 17:10 UTC, bambruysk commented on internal/storage/storage_test.go
> +			assert.Equal(t, fmt.Sprintf("%v", tt.want), fmt.Sprintf("%v", valueBack), "returned value not equal to expected")
Лучше бы хранилиже использовалось как интрефейс тогда можно было бы использовать моки

2023-12-27 06:32 UTC, sebasttiano commented on internal/handlers/handler.go
> +}
Это было легаси, удалил

2023-12-27 06:38 UTC, sebasttiano commented on cmd/agent/main_test.go
> +			assert.Equal(t, tt.args.reportInterval, endTime-startTime)
Добавил еще проверку, что после отправки метрик на сервер не возвращаются ошибки

2023-12-27 06:39 UTC, sebasttiano commented on cmd/agent/main.go
> +		defer res.Body.Close()
закрываю сразу

2023-12-28 14:58 UTC, bambruysk approved these changes
Хорошо

2023-12-28 19:40 UTC, merged